name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 7 * * 1"  # runs every Monday at 07:00 AM UTC (08:00 AM CET / 09:00 AM CEST)
  workflow_dispatch:

concurrency:
  group: pre-commit-autoupdate
  cancel-in-progress: true

permissions: {}

jobs:
  auto-update:
    name: Auto-update hooks
    runs-on: ubuntu-latest
    permissions:
      contents: write       # required for creating a commit to a branch
      pull-requests: write  # required for creating/updating PR, adding labels and reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update hooks
        id: update
        run: |
          OUTPUT="$(pre-commit autoupdate)"
          echo "$OUTPUT" >> "$GITHUB_STEP_SUMMARY"
          {
            echo 'logs<<EOF'
            echo "$OUTPUT"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: bump version(s)
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: update-pre-commit-hooks
          delete-branch: true
          title: "chore(pre-commit): update hooks"
          body: ${{ steps.update.outputs.logs }}
          labels: dependencies
          reviewers: mnau23
