name: Update sitemap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pre-commit-autoupdate
  cancel-in-progress: true

permissions: {}

jobs:
  update-sitemap:
    name: Build and deploy
    runs-on: ubuntu-latest
    # skip draft PRs and those opened by bots
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
    permissions:
      contents: write  # required for creating a commit to a branch
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Generate sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@abcba11c9eb198b392608f596fd939c9fb9e3edd # v1.9.2
        with:
          base-url-path: https://emanuele.codes/
          path-to-root: dist

      - name: Format sitemap
        run: |
          sudo apt-get install -y libxml2-utils
          xmllint --format dist/sitemap.xml > dist/tmp.xml
          mv dist/tmp.xml dist/sitemap.xml

      - name: Commit to current branch
        id: commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "[action] update sitemap"
          file_pattern: "dist/sitemap.xml"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Show stats
        run: |
          echo "File saved at: ${{ steps.sitemap.outputs.sitemap-path }}" >> $GITHUB_STEP_SUMMARY
          echo "Number of URLs tracked: ${{ steps.sitemap.outputs.url-count }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.commit.outputs.changes_detected }}" = "true" ]; then
            echo "Sitemap updated!" >> $GITHUB_STEP_SUMMARY
          else
            echo "No changes detected!" >> $GITHUB_STEP_SUMMARY
          fi
